### PR TITLE
remove useless wrapped

### PR DESCRIPTION
**Pull request by Et7f3**
their is already a file named `extLib.ml` that play the role of including all other files.

### CODE REVIEW

**Comment by dra27** [comment]
This patch now requires any software using ExtLib to either `open ExtLib` or have `-open ExtLib` in flags, doesn't it?

**Comment by dra27** [comment]
The upstream ExtLib also doesn't include all the other files? See https://github.com/ygrek/ocaml-extlib/blob/master/src/extLib.ml

**Comment by dra27** [comment]
Oops - it's actually worse than that - you're not just namespacing them away, you're hiding the modules not mentioned in ExtLib.ml completely! To see the problem, try running `dune utop .` and run `#show_module Unzip` both with and without your change.

**Comment by Et7f3** [comment]
Ok sorry I should have double checked.

**Pull request closed without merging**
